//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.01.27 at 03:47:49 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "com.vn2bs.webservices.byt.thutuc1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package thutuc1.byt.webservices.vn2bs.com;
