spring.application.name=nsw-services
server.port=8084

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=flow1

# JPA Configuration
spring.datasource.url=jdbc:mysql://localhost:3316/nsw_adapter
spring.datasource.username=root
spring.datasource.password=rootpassword