<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.vn2bs</groupId>
		<artifactId>handle-multiple-service-gateway-sample</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<groupId>com.vn2bs</groupId>
	<artifactId>nsw-adapter</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>nsw-adapter</name>
	<description>Adapter đầu Hải quan</description>

	<properties>
		<liquibase.version>4.33.0</liquibase.version>
		<liquibase-maven-plugin.version>5.0.0</liquibase-maven-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.vn2bs</groupId>
			<artifactId>common</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
			<version>${liquibase.version}</version>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.liquibase</groupId>
					<artifactId>liquibase-secure-maven-plugin</artifactId>
					<version>${liquibase-maven-plugin.version}</version>
					<configuration>
						<!-- <propertyFile>liquibase.properties</propertyFile> -->
						<changeLogFile>src/main/resources/config/liquibase/master.xml</changeLogFile>
						<url>jdbc:mysql://localhost:3316/nsw_adapter</url>
						<driver>com.mysql.jdbc.Driver</driver>
						<username>root</username>
						<password>rootpassword</password>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>